#!/bin/sh

set -eu

echo $DOCKER_HOST
docker version
mkdir -p circle .dobi/images

docker build -t dobi-dev -f dockerfiles/Dockerfile.build .
docker run \
    -v $PWD:/go/src/github.com/dnephin/dobi \
    dobi-dev \
    bash -ec "pwd; ls; glide install; go build -o circle/dobi ."
